### ISSUE TITLE
Asset pipeline task instead of source file task

### ISSUE THREAD

**Issue by huntc** [rgcottrell/sbt-html-minifier#1]
I recommend turning this into an asset pipeline task instead of it being a source file task. I would want this to occur only during the building of a distribution, not in my regular developer loop.

**Comment by rgcottrell** [comment]
I think this is a good idea. I actually thought about doing this after I finished writing the plugin and got a better understanding of the strengths and weaknesses of source and pipeline plugins.

**Comment by huntc** [comment]
Cool. FYI pipeline stages can also be configured to work during dev:

``` scala
pipelineStages in Assets := Seq(...
```

The `in Assets` is the significant bit.

**Comment by rgcottrell** [comment]
Alright, the project has now been converted over to be an asset pipeline task. Thanks again for the suggestion!

**Comment by huntc** [comment]
That's just awesome - thanks!
