### ISSUE TITLE
Scripted tests and test project

### ISSUE THREAD

**Issue by huntc** [rgcottrell/sbt-html-minifier#2]
Going forward you might want to adopt scripted for testing and the test sub project approach for rapid turn around when testing plugins. Check out sbt-uglify in this regard and lemme know if you require further guidance.

**Comment by rgcottrell** [comment]
Cool. I felt a little guilty checking this in without tests, but wanted to first make sure I learned how to integrate with the framework. I'll take a look at the test sub projects and see what it takes to add one.

**Comment by rgcottrell** [comment]
I've added a scripted test for the project. It runs fine if I add a package.json and install the node modules necessary before running the test. However, automatic installation of the node modules doesn't seem to be happening. Am I missing something to trigger this?

**Comment by rgcottrell** [comment]
It looks like dependsOn(nodeModules in Assets) was necessary to install the package.json Node modules before the plugin runs. The tests now run successfully!

Are there any tests in particular you would like to see, or can I close out this issue?

**Comment by huntc** [comment]
No, nothing in particular. Thanks.
