### ISSUE TITLE
Html minification on runtime

### ISSUE THREAD

**Issue by nonameplum** [rgcottrell/sbt-html-minifier#3]
Hi,

I wanted to ask if it is possible to minify html on run time? E.g. I'm creating table in loop in twirl play framework template. I want to minify this dynamically created html view using your plugin.

**Comment by rgcottrell** [comment]
No, unfortunately this plugin won't work for dynamic content. The sat-web plugins are intended to be used on static assets at compile time.

If you are serving your site behind Apache or Nginx, then you might want to consider Google's PageSpeed module (https://developers.google.com/speed/pagespeed/module), which contains filters that can apply optimizations to dynamically generated HTML.
